# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets: []
userService:
  enabled: true
  name: "user-service"
  image: "pttgcdevopsacr09.azurecr.io/user-service" #Change this `pttgcdevopsacr02.azureecr.io` to your own acr
  tag: "dfdada20817eed41632d32706bf66c82c72b8a68"
  pullPolicy: IfNotPresent
  servicePort: 8080
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
    limits:
      memory: 1G
      cpu: 500m
  domainName: "api-cluster09.z-unified.com" # Change this to your domain that provided in spreadsheet
ingress:
  enabled: true
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
